on: 
  # Automatically created tags
  create:
  # Manually created and pushed tags
  push:
    tags: ["*"]
  # Run on specific tag from the workflow panel
  workflow_dispatch:

name: Release

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: sh download.sh
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            BabelStoneHanBasic.ttf
            BabelStoneHanExtra.ttf
            BabelStoneHanPUA.ttf
            LICENSE
