on: 
  push:
    tags: ["*"]
  workflow_dispatch:

name: Release

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: sh download.sh
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            BabelStoneHanBasic.ttf
            BabelStoneHanExtra.ttf
            BabelStoneHanPUA.ttf
            LICENSE