on:
  # Call from the update workflow
  workflow_call:
    inputs:
      tag_name:
        type: string
        required: true
  # Manually created and pushed tags
  push:
    tags: ["*"]
  # Run on specific tag from the workflow panel
  workflow_dispatch:

name: Release

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: sh download.sh
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag_name }}
          files: |
            BabelStoneHanBasic.ttf
            BabelStoneHanExtra.ttf
            BabelStoneHanPUA.ttf
            LICENSE
