on:
  workflow_dispatch:
    inputs: {}
  schedule:
  - cron: "0 3 * * *"

name: Update ufo

jobs:
  update:
    name: Update ufo
    runs-on: ubuntu-latest
    outputs:
      updated: ${{ steps.updated.outputs.updated }}
      TAG_NAME: ${{ steps.tag.outputs.TAG_NAME }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: sh download.sh
      - run: sh build.sh 
      - name: Check if it has been updated
        run: |
          [[ -z $(git status -s) ]] &&
            echo "updated=false" >> $GITHUB_OUTPUT ||
            echo "updated=true" >> $GITHUB_OUTPUT
        id: updated
      - name: Commit changes
        if: steps.updated.outputs.updated == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update"
          git push --force-with-lease origin
      - name: Tag
        id: tag
        if: steps.updated.outputs.updated == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export TAG_NAME=`date +'%Y%m%d'`-beta
          git tag -m "$TAG_NAME" "$TAG_NAME"
          git push origin "$TAG_NAME"
          echo "TAG_NAME=$TAG_NAME" >> "$GITHUB_OUTPUT"

  release:
    name: Release
    needs: update
    uses: ./.github/workflows/release.yml
    if: needs.update.outputs.updated == 'true'
    permissions:
      contents: write
    with:
      tag_name: ${{ needs.update.outputs.TAG_NAME }}

